version: '3.7'
services:
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry
    ports:
      - 8761:8761
  gateway:
    build: gateway
    ports:
      - 80:4000
  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  account-service:
    build: account-service
    ports:
      - 6000:6000

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000

  notification-service:
    build: notification-service
    ports:
      - 8000:8000

  monitoring:
    build: monitoring
    ports:
     - 8080:8080

  turbine-stream-service:
    build: turbine-stream-service
    ports:
     - 8989:8989